from .shared import CATEGORY
import torch

# Warning: many parts generated by AI,
# I invented input/output interface
# and tried to follow along to see if everything else makes sense.

# Tested for MiniMax H3 only, 
# but might coincidentally work for other audio-video models as well,
# if constants are adjusted

MINIMAX_H3_PARAMS = {
    # Minimax: 17k+5 grid, where k is integer
    # Valid frame counts must evaluate to 5 modulo 17, 
    # resulting in the mandatory frame lengths such as: 5, 22, 39, 56, 73, 90, 107, 124...
    "audio_token_rate": 40,
    "frame_multi": 17.0,
    "frame_offset": 5.0,
    "min_latent_temporal_tokens": 2.0
}


# Based on https://github.com/Comfy-Org/ComfyUI/pull/15375
# and requires the latest ComfyUI with that PR merged.
# Kudos to drozbay (ablejones) and Kijai for providing ideas
# that were implemented almost "as is" for this node,
# all mistakes are mine (and AIs).
class LatentAVTailMaskedExtender:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        return {"required": {
            "empty_av": ("LATENT", ),
            "overlap_video_tail_seconds": ("FLOAT", {"default": 1.0, "min": 1.0, "max": 60.0, "step": 0.1}),
            "video_fps": ("FLOAT", {"default": 24.0, "min": 1.0, "max": 120.0, "step": 0.1})
        },
        "optional": {
            "loaded_av": ("LATENT", )
        }}

    RETURN_TYPES = ("LATENT", )
    RETURN_NAMES = ("av_latent", )
    FUNCTION = "run"
    CATEGORY = CATEGORY

    def run(self, empty_av, overlap_video_tail_seconds, video_fps, loaded_av=None):
        if loaded_av is None:
            return (empty_av, )        

        # might support other models in the future?
        params = MINIMAX_H3_PARAMS
        audio_token_rate = params["audio_token_rate"]
        frame_multi = params["frame_multi"]
        frame_offset = params["frame_offset"]
        min_latent_temporal_tokens = params["min_latent_temporal_tokens"]

        # 1. Convert requested seconds to target frames
        target_frames = overlap_video_tail_seconds * video_fps
        
        # 2. Find the closest integer 'k' multiplier for the 17k + 5 constraint
        # Ensure k is at least 0 to prevent negative frame lengths
        k = max(0, int(round((target_frames - frame_offset) / frame_multi)))
        
        # 3. Calculate the strictly snapped synchronized frames
        snapped_video_frames = int(k * frame_multi + frame_offset)
        
        # 4. Calculate the required video and audio tokens based on the snapped frames
        video_tail_tokens = int(k * frame_offset + min_latent_temporal_tokens)
        audio_tail_tokens = int(round(snapped_video_frames * (audio_token_rate / video_fps)))

        return self.extend_masked(loaded_av, empty_av, video_tail_tokens, audio_tail_tokens)


    def extend_masked(self, loaded_av, empty_av, video_tail_tokens, audio_tail_tokens):
        out_av = loaded_av.copy()
        
        old_v = loaded_av["samples"]
        new_v = empty_av["samples"]

        # Unnest combined AV subtensors
        old_tensors = old_v.unbind()
        old_video_tensor = old_tensors[0]
        old_audio_tensor = old_tensors[1]
        
        new_tensors = new_v.unbind()
        new_video_tensor = new_tensors[0]
        new_audio_tensor = new_tensors[1]

        # ==========================================
        # 1. VIDEO PROCESSING
        # ==========================================
        dims_v = len(old_video_tensor.shape)
        # Dynamic slice: [Batch, Channels, Frames, Height, Width] -> t_dim=2
        t_dim_v = 2 if dims_v >= 3 else 0

        idx_tail_v = [slice(None)] * dims_v
        idx_tail_v[t_dim_v] = slice(-video_tail_tokens, None)
        tail_v = old_video_tensor[tuple(idx_tail_v)]
        
        idx_rem_v = [slice(None)] * dims_v
        idx_rem_v[t_dim_v] = slice(video_tail_tokens, None)
        rem_v = new_video_tensor[tuple(idx_rem_v)]
        
        combined_v = torch.cat((tail_v, rem_v), dim=t_dim_v)
        
        # Spatial mask initialization
        F_v = combined_v.shape[t_dim_v]
        H_v = combined_v.shape[-2]
        W_v = combined_v.shape[-1]
        
        # Initialize as 1.0 (denoise/generate) and set tail to 0.0 (preserve)
        mask_v = torch.ones((F_v, H_v, W_v), dtype=torch.float32, device=combined_v.device)
        mask_v[:video_tail_tokens, :, :] = 0.0 
        
        # Enforce exact reshaping logic from ComfyUI's SetLatentNoiseMask
        mask_v_reshaped = mask_v.reshape((-1, 1, mask_v.shape[-2], mask_v.shape[-1]))

        # ==========================================
        # 2. AUDIO PROCESSING
        # ==========================================
        dims_a = len(old_audio_tensor.shape)
        t_dim_a = -1
        
        idx_tail_a = [slice(None)] * dims_a
        idx_tail_a[t_dim_a] = slice(-audio_tail_tokens, None)
        tail_a = old_audio_tensor[tuple(idx_tail_a)]
        
        idx_rem_a = [slice(None)] * dims_a
        idx_rem_a[t_dim_a] = slice(audio_tail_tokens, None)
        rem_a = new_audio_tensor[tuple(idx_rem_a)]
        
        combined_a = torch.cat((tail_a, rem_a), dim=t_dim_a)
        
        # Map exact dimensions for native broadcasting: [Batch, Freq, Time]
        B_a = combined_a.shape[0]
        Freq_a = combined_a.shape[-2]
        Time_a = combined_a.shape[-1]
        
        # Initialize as 1.0 (denoise/generate) and set tail to 0.0 (preserve)
        mask_a = torch.ones((B_a, Freq_a, Time_a), dtype=torch.float32, device=combined_a.device)
        mask_a[:, :, :audio_tail_tokens] = 0.0 
        
        # Enforce exact reshaping logic from ComfyUI's SetLatentNoiseMask
        mask_a_reshaped = mask_a.reshape((-1, 1, mask_a.shape[-2], mask_a.shape[-1]))

        # ==========================================
        # 3. RECONSTRUCT OUTPUTS
        # ==========================================
        tensors_out = [combined_v, combined_a]
        masks_out = [mask_v_reshaped, mask_a_reshaped]
        
        # Repackage modified components into identical NestedTensor types
        out_av["samples"] = type(old_v)(tensors_out)
        out_av["noise_mask"] = type(old_v)(masks_out)
                
        return (out_av, )